### PR TITLE
Replace GitHub actions CI by Azure pipelines

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Review by shadeMe — APPROVED** [review]
LGTM! We still need to enable CI support on the Azure dashboard, I take?

**Comment by danieldk** [comment]
> LGTM! We still need to enable CI support on the Azure dashboard, I take?

Yeah.

**Comment by adrianeboyd** [comment]
https://dev.azure.com/explosion-ai/Public/_build/results?buildId=21911&view=results

**Comment by danieldk** [comment]
Abandoning this PR, since we want to move to GH actions. This PR would move in the opposite direction.

**Pull request closed without merging**
