### PR TITLE
Add character encoder

### PR DESCRIPTION
**Pull request by danieldk**
## Description

This encoder splits a token into characters and looks up their identifiers. The primary motivation for adding this encoder is that our standard model for Japanese requires it. Along with the encoder itself, `curated-transformers.CharEncoderLoader.v1` is added to load character vocabularies and support to load Japanese character-based encoders is added to `curated-transformers.HFPieceEncoderLoader.v1`.

### Types of change

Feature

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Nothing jumps out at me, but I didn't try to double-check the token IDs in the tests or anything. I was surprised that the vocab file is just a plain `.txt` list, but I guess that's the typical format?

**Comment by danieldk** [comment]
> I was surprised that the vocab file is just a plain `.txt` list, but I guess that's the typical format?

Yeah, luckily character vocabs and wordpiece vocabs are plain text.

**Review by polm — APPROVED** [review]
The fugashi/Sudachi parts look good to me! I'm not as familiar with the HF parts, but nothing looked off there either.

**Comment by danieldk** [comment]
> "luckily" is not how I'd describe it.

Betty than some whacky JSON format, re-encoding UTF-8 pieces in its own encoding 😱 .

**Pull request merged**
